### PR TITLE
Feature/fix issue492

### LINKED ISSUE #492: [derivatives] Lack of the state modification for liquidity pool using KVStore just for it
- Remove KVStore just for liquidity pool since it can be performed by bank keeper and module account
- Confirm derivatives module account is in Blocked Addresses to receive funds via send msg from an address
- Replace state modification functions using the new method

### PR DESCRIPTION
**Pull request by taiki1frsh**
close #492 

- Modification based on 492
- Fix tests
- Add account keeper to handle query against module account

### CODE REVIEW

File: x/derivatives/types/pool.go [hunk 1]
```diff
@@ -62,3 +62,10 @@ func IsValidDepositForPool(deposit sdk.Coin, acceptableAssets []PoolAssetConf) b
 	}
 	return false
 }
+
+// CalcTargetAmountInPool is used to calculate the target amount of the asset in the pool.
+// The target amount is calculated by the formula:
+// targetAmount = poolMarketCap * weight / price
+func CalcTargetAmountInPool(weight, price, poolMarketCap sdk.Dec) sdk.Int {
+	return poolMarketCap.Mul(weight).Quo(price).TruncateInt()
```
Comment (jununifi) [inline x/derivatives/types/pool.go:70]: I think price zero case should be considered

File: x/derivatives/types/keys.go [hunk 2]
```diff
@@ -27,19 +27,16 @@ const (
...
-	KeyPrefixNetPositionAmount     = "net_position_amount"
-	KeyPrefixLastPositionId        = "last_position_id"
+	KeyPrefixPosition                 = "position"
+	KeyPrefixUserPosition             = "user_position"
+	KeyPrefixPerpetualFutures         = "perpetual_futures"
+	KeyPrefixPerpetualOptions         = "perpetual_options"
+	KeyPrefixNetPositionAmount        = "net_position_amount"
+	KeyPrefixLastPositionId           = "last_position_id"
+	// TODO: KeyPrefixAccumulatedFee is unused. Remove it if it won't be necesary.
 	KeyPrefixAccumulatedFee        = "accumulated_fee"
```
Comment (jununifi) [inline x/derivatives/types/keys.go:40]: @KimuraYu45z this item will need to be removed?

File: x/derivatives/types/expected_keepers.go [hunk 3]
```diff
@@ -29,3 +30,8 @@ type PricefeedKeeper interface {
 	// These are used for testing TODO replace mockApp with keeper in tests to remove these
 	SetParams(sdk.Context, pftypes.Params)
 }
+
+type AccountKeeper interface {
```
Comment (jununifi) [inline x/derivatives/types/expected_keepers.go:34]: I think account keeper is not used other than GetModuleAddress and this could be removed if there's no further use case since GetModuleAddress can be replaced with authtypes.NewModuleAddress

File: x/derivatives/types/pool.go (hunk 1 above)
Comment (taiki1frsh) [reply x/derivatives/types/pool.go:70]: Yes, I def agree **in general.**
that's why I created this https://github.com/UnUniFi/chain/issues/446.

But, if we use sdk.Int or sdk.Dec for the calculation of the division, it will cause panic if the dividing num is zero, right?
So, I think this issue will be better to be addressed in a more structural way for all the other part at once. 
What do you think?

File: x/derivatives/keeper/pool.go [hunk 4]
```diff
@@ -37,28 +37,13 @@ func (k Keeper) IsAssetAcceptable(ctx sdk.Context, denom string) bool {
...
-	return coin
-}
-
-func (k Keeper) SetAssetBalance(ctx sdk.Context, coin sdk.Coin) {
-	store := ctx.KVStore(k.storeKey)
-	bz := k.cdc.MustMarshal(&coin)
-	store.Set(types.AssetDepositKeyPrefix(coin.Denom), bz)
+// GetAssetBalanceInPoolByDenom is used to get token balance of "derivatives" module account which is the liquidity pool.
+func (k Keeper) GetAssetBalanceInPoolByDenom(ctx sdk.Context, denom string) sdk.Coin {
+	derivModAddr := k.accountKeeper.GetModuleAddress(types.ModuleName)
```
[the remark this answers is not in the document]
Comment (taiki1frsh) [reply x/derivatives/keeper/pool.go:42]: oh, didn't know that.
will support that way by removing account keeper injection.

File: x/derivatives/types/expected_keepers.go (hunk 3 above)
Comment (jununifi) [reply x/derivatives/types/expected_keepers.go]: Okay cool

**Review by jununifi — APPROVED** [review]
LGTM

File: x/derivatives/types/keys.go (hunk 2 above)
Comment (KimuraYu45z) [reply x/derivatives/types/keys.go:40]: Sorry I forgot...
